#---------------------------------------------------
# Aim: Load necessary libraries to regenerate the results of the publication
# Author: B. Rentroia Pacheco
#---------------------------------------------------

library(openxlsx)
library(EnsDb.Hsapiens.v75)
library(org.Hs.eg.db)
library(ensembldb)
library(biomaRt)
library(httr) 
library(gtsummary)
library(plyr)
library(dplyr)
library(tidyr)
library(scales)
library(gridExtra)
library(ggplot2)
library(ggpubr)
library(patchwork)
library(mice)
library(maftools)
library(sigminer)
library(forcats)
library(ggvenn)
library(readr)
library(yaml) 
library(trackViewer)
library(officer)
library(rvg)
library(purrr)
library(survival)
library(stringr)
library(glmnet)
library(ranger)
library(tidytext)
library(ComplexUpset)
